### ISSUE TITLE
Is this dead ?

### ISSUE THREAD

**Issue by Armaldio** [LinusU/wext-shipit#1]
I'd like to use this, is it still working ?
Do you plan to add remaining browsers ?

**Comment by LinusU** [comment]
> is it still working ?

I created this 24 days ago 😆 I know that JS land moves quickly, but I wouldn’t call it dead yet

I’m using this to ship a production extension so it’s definitely working.

Unfortunately Edge doesn’t support a crucial API for the app & extension I’m working on, so I probably wont implement that in the near future (at least during office hours, I would love to get some great idea for a small fun extension that I could build). 

Safari’s process is quite... “basic”, compared to the other ones. You basically fill in everything as when you publish a new extension, and you also have to host the extension somewhere for them to download, you can’t upload it to them directly...

That being said I’ll probably get to that in a few weeks since I really want that part automated now that they have _finally_ approved the extension.

Hope that this answers everything 💅

**Comment by Armaldio** [comment]
Yeah, dead was probably a bit too much ^^ but I didn't saw so much updates so I tough it's like many other repos a "push and forget"
Also, from where I got link to this, the firefox upload to the addon store was a "dirty hack" so maybe it doesn't worked anymore.

I'm really happy to know that a solution like your exists.
Thanks for your time answering my questions :)
